### ISSUE TITLE
Stack: Regardless of gutter value passed in "pf-m-gutter" is set on the Stack

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#2050] opened 2019-05-21 15:09 UTC
It doesn't matter what value I pass in for a gutter to <Stack> the "pf-m-gutter" class is added to the stack.

**Comment by christianvogt** [comment] 2019-06-25 17:31
Same problem occurs on `Split`

**Comment by jessiehuff** [comment] 2019-06-25 20:37
I don't think the modifiers exist [in core](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/layouts/Stack/stack.scss) so even though we changed the class name it doesn't do anything.

**Comment by mcoker** [comment] 2019-07-01 19:43
@jeff-phillips-18 we don't currently support modifying the gutter size on these layouts. @kybaker and I have talked about it and if you need to override the gutter size, you'll need to write a CSS override or use a utility class. The values for the `gutter` prop in the react layouts should be removed so the gutter is either enabled or disabled. I filed an issue for that here - https://github.com/patternfly/patternfly-react/issues/1982

**Comment by dlabaj** [comment] 2019-07-08 19:25
duplicate of #1982

**Comment by tlabaj** [comment] 2019-08-06 15:51
Closing this since it is duplicate.

**Closed by tlabaj** 2019-08-06 15:51 UTC
Labels: PF4, bug :bug:, p1
