### ISSUE TITLE
react-docs: Upgrade to Gatsby v2

### ISSUE THREAD

**Issue by dmiller9911** [patternfly/patternfly-react#412] opened 2018-06-20 17:21 UTC
Gatsby V2 fixes most, if not all, of the workarounds that had to be put in place for the current docs.  Upgrading will also open the door for a more seamless docs generation.

**Comment by LHinson** [comment] 2018-09-14 15:40
@dmiller9911 are you actively working on this? If not, please remove your name so others know the issue is available and still a to-do.

**Comment by tlabaj** [comment] 2019-01-18 15:30
closed by PR #1179

**Closed by tlabaj** 2019-01-18 15:30 UTC
Labels: PF4, infrastructure, p1
