### ISSUE TITLE
Bug - Select/Dropdown - cannot set menuHeight on scrollable menu

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#10028] opened 2024-01-19 18:19 UTC
The `menuHeight` prop on the `MenuContent` component is not accessible to the `Select` or `Dropdown` components.

the `Menu`'s feature can be viewed at this example: https://www.patternfly.org/components/menus/menu/#scrollable-menu-with-custom-height 

The `MenuContent` component is not exposed, nor is it passed any props by via the Select or Dropdown components.

**Comment by tlabaj** [comment] 2024-01-25 15:17
Duplicate of https://github.com/patternfly/patternfly-react/issues/10024

**Closed by tlabaj** 2024-01-25 15:17 UTC
Labels: bug
