### ISSUE TITLE
PF4 Tooltip: Module not found error

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#2331] opened 2019-06-22 01:15 UTC
Installed the latest pre-release packages and encountered this module error with the tooltip component.

<img width="855" alt="Screen Shot 2019-06-21 at 9 13 32 PM" src="https://user-images.githubusercontent.com/17481322/59957758-968fe380-9469-11e9-86cf-a480dc18c025.png">

Package versions:
<img width="288" alt="Screen Shot 2019-06-21 at 9 15 25 PM" src="https://user-images.githubusercontent.com/17481322/59957766-b7f0cf80-9469-11e9-9043-09d3ac0d8ddf.png">

**Comment by rachael-phillips** [comment] 2019-06-24 12:51
Hi @dlabrecq will this be a blocking change for our users? @tlabaj making you aware.

**Comment by dlabrecq** [comment] 2019-06-24 17:45
Yes, this is a blocker. I cannot update Cost management to use the latest PF4 packages if our build will not compile.

**Comment by rachael-phillips** [comment] 2019-06-25 12:45
@jschuler is going to take a look at this @dlabrecq !

**Comment by jschuler** [comment] 2019-06-25 13:20
Hi @dlabrecq , having trouble reproducing this
https://codesandbox.io/s/pedantic-visvesvaraya-t0lzo
Can you perhaps clear out your node_modules folder and try it again?

**Comment by dlabrecq** [comment] 2019-06-25 14:29
I installed the latest pre-release packages and no longer see the tooltip error.

<img width="277" alt="Screen Shot 2019-06-25 at 10 29 04 AM" src="https://user-images.githubusercontent.com/17481322/60106986-1650d300-9734-11e9-868d-9a60c11751f5.png">

However, I see 6 new TS error with tabs. Looks like variant should be optional because there is a default.

<img width="800" alt="Screen Shot 2019-06-25 at 10 27 15 AM" src="https://user-images.githubusercontent.com/17481322/60106933-033e0300-9734-11e9-86b7-c1418b55627c.png">

**Comment by tlabaj** [comment] 2019-06-25 15:13
Closing this since the latest package resolves he issue.

**Closed by tlabaj** 2019-06-25 15:13 UTC
Labels: PF4, bug :bug:, p1

**Comment by dlabrecq** [comment] 2019-06-25 15:29
I have to open a new issue for tabs?

**Comment by tlabaj** [comment] 2019-06-25 15:30
At Dan I was about to open it.  You can open it is you want to.
