### ISSUE TITLE
LabelGroup's parameter isCompact=true does not make nested labels compact 

### ISSUE THREAD

**Issue by gkarat** [patternfly/patternfly-react#6815] opened 2022-01-18 09:46 UTC
**Describe the issue. What is the expected and unexpected behavior?**

Use `LabelGroup` and set its parameter `isCompact` to true. Then, nest several `Label`s within the group. The labels are not of the "compact" version and have the standard size.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, non-blocking (providing `isCompact` to each of the `Label`s solves the issue).

**What is your product and what release version are you targeting?**

https://github.com/RedHatInsights/ocp-advisor-frontend/pull/87
@patternfly/react-core 4.182.0

**Comment by eliranmal** [comment] 2022-01-22 18:19
from initial investigation, several conclusions arise:

1. when `isCompact` is applied to every label in the group, they render fine.

1. looking closely, the label's text size does change to the smaller variant, but its layout (box-model) is broken, and it somehow remains in its original height.
this looks like the heart of the matter; this broken layout follows from the label and/or label group item elements having an `inline-flex` display, and if you remove any of these, the problem goes away.

1. internally, the [current implementation][1] only explicitly ties the group's `isCompact` property to the *more...* button's compact state - which is shown when extra child elements are present besides the labels (e.g. when using `isEditable`). no other behavior is tied to that property it seems.
this looks right - we wouldn't want to tie any imperative (unnecessary) behavior, only handle the proper combinations of the underlying style declarations.

all of these lead me to think that this issue should be addressed in the core repository.  
i'll do some deeper investigation to verify and, if necessary, update the issue and post the link here.




[1]: https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/LabelGroup/LabelGroup.tsx#L171-L181

**Comment by eliranmal** [comment] 2022-01-26 17:10
@gkarat, your expectation seem to be that assigning `isCompact` to the label group will enforce all nested labels to the compact mode (regardless of their own mode?).
it may be a reasonable one, as other components behave in a similar way (delegate the component level prop to a patternfly modifier classname), but it's not how the label group component works at this point.

my current fix only amends the height of compact labels, when mixed with standard labels.

please let me know if you're still interested in meeting the original expectation above, as this will require a different kind of change (it'd be a feature request, not a bug fix, and would require further work).

**Comment by eliranmal** [comment] 2022-02-02 00:32
@mcarrano - sure thing! see [my comment to your comment, there][1].


[1]: https://github.com/patternfly/patternfly/issues/4638#issuecomment-1027440947

**Comment by eliranmal** [comment] 2022-02-28 19:05
@gkarat, @tlabaj, @mcarrano - FYI, the core issue (#4638) was closed as a `wontfix`, IMO this one should be as well.

**Comment by mcarrano** [comment] 2022-02-28 21:02
That makes sense. Thanks for your attention to this @eliranmal .

**Closed by mcarrano** 2022-02-28 21:02 UTC
