### ISSUE TITLE
index.js: missing ApplicationLauncher* export  ?

### ISSUE THREAD

**Issue by sonicold** [patternfly/patternfly-react#605] opened 2018-09-11 09:15 UTC
It seems that we cannot import those components correctly.

Imports should look like:
```
import ApplicationLauncher from 'patternfly-react';
import ApplicationLauncherItem from 'patternfly-react';
```

Errors:
```
warning.js:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports
```

Workaround:
```
import ApplicationLauncher from 'patternfly-react/dist/js/components/ApplicationLauncher/ApplicationLauncher.js';
import ApplicationLauncherItem from 'patternfly-react/dist/js/components/ApplicationLauncher/ApplicationLauncherItem.js';
```

Versions:
```
react: "^16.3.2"
patternfly-react: "^2.17.2"
patternfly: "^3.45.0"
```

**Comment by jeff-phillips-18** [comment] 2018-09-11 11:33
Duplicate of #576

**Closed** 2018-09-11 11:33 UTC
