### ISSUE TITLE
Select component height in menu open is wrong

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#1931] opened 2019-05-06 10:47 UTC
Seelct component height when is open difference between core and react:

core - https://pf4.patternfly.org/components/Select/examples/

react http://patternfly-react.surge.sh/patternfly-4/components/select/

**Comment by aljesusg** [comment] 2019-05-06 10:47
@jessiehuff

**Comment by aljesusg** [comment] 2019-05-06 10:48
The same behaviour with dropdown 

http://patternfly-react.surge.sh/patternfly-4/components/dropdown/

**Comment by abalakh** [comment] 2019-05-07 12:53
Is this issue about page layout, i.e. widget example section (`<div class="example">`) has always fixed size so opening any expandable object inside it introduces scrollbars?
![image](https://user-images.githubusercontent.com/11719030/57300638-eac04d80-70df-11e9-94a1-3e1eb53fbb4d.png)
Assuming it is, then if it's gonna be fixed on specific pages only - at least select, dropdown, context selector and paginator (per page selector) pages are affected.
But it's a generic issue across all the pages, so i hope it will be fixed for all pages.

**Comment by quarckster** [comment] 2019-05-07 12:58
a dupe of https://github.com/patternfly/patternfly-react/issues/1910

**Comment by kmcfaul** [comment] 2019-05-08 17:08
This is caused by updates to the example code generator as we move towards the new website. Please use https://www.patternfly.org/v4

**Closed by kmcfaul** 2019-05-08 17:08 UTC
