### ISSUE TITLE
Props missing from Text Input component page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#4204] opened 2020-05-06 18:55 UTC
There is no Props section on the Text Input page: https://www.patternfly.org/v4/documentation/react/components/textinput

cc @tlabaj

**Comment by evwilkin** [comment] 2020-05-07 17:53
Related to https://github.com/patternfly/patternfly-react/issues/4197

**Comment by redallen** [comment] 2020-05-07 17:53
Duplicate of #4197

**Closed by redallen** 2020-05-07 17:53 UTC
Labels: bug :bug:
