### ISSUE TITLE
Options menu - deprecate and merge with Select

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#8466] opened 2022-12-20 15:07 UTC
Want to deprecate the existing Options menu component in favor of adding this as a new variant of the Select Next component. Work requested includes:

* Creating a new example of the Select that demonstrates Options menu functionality.
* Deprecating the existing Options menu.

**Comment by tlabaj** [comment] 2023-01-25 01:42
duplicate of #8075 8075

**Closed by tlabaj** 2023-01-25 01:42 UTC
Labels: feature request, 🔷 PatternFly 5
