### ISSUE TITLE
Test error: Cannot find the Select's role

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#10926] opened 2024-08-28 16:05 UTC
**Please describe the issue**

Test fails due to `Unable to find role="option"` error, related to Select. This test worked with v5, but no longer works with v6.

**Are there visuals for this issue? Please provide screenshots**

Error
![Screenshot 2024-08-28 at 12 03 45 PM](https://github.com/user-attachments/assets/99e9ba83-7013-4692-8077-8964ef9ca348)

![Screenshot 2024-08-28 at 12 03 59 PM](https://github.com/user-attachments/assets/a72cb137-f40d-4710-8e7d-fd60898c020a)

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**

Test
https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModel/updateRateModel.test.tsx#L300

Tested component
https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/components/rateForm/rateForm.tsx#L130

The tested component drills down to this Select
https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/components/selectWrapper/selectWrapper.tsx#L100

**Comment by wise-king-sullyman** [comment] 2024-09-24 15:23
This failure appears to be caused because the Popper menu is being set to aria-disabled after a selection is made, causing the RTL query to not be able to find the menu options without the `{hidden: true}` option being passed. This behavior started occurring with [our change to Poppers default appendTo value](https://github.com/patternfly/patternfly-react/pull/10675) and can be resolved by either passing that `hidden` option to the RTL queries or changing the Select's `appendTo` back to `inline`.

Also it seems to be a strange interaction between the internals of Popper and Jest/JSDOM as I haven't been able to reproduce this in a real browser, if anyone is though please let me know.

**Comment by kmcfaul** [comment] 2024-09-24 18:37
[#4277](https://github.com/patternfly/patternfly-org/issues/4277) will track the work to improve documentation.

**Closed by kmcfaul** 2024-09-24 18:37 UTC
Labels: P1 :star:, v6 Beta bug
