### ISSUE TITLE
Bug - [MenuItem] - [Documentation is missing]

### ISSUE THREAD

**Issue by jelly** [patternfly/patternfly-react#10201] opened 2024-03-26 17:06 UTC
**Describe the problem**

The MenuItem component property documentation is missing, as for Menu and MenuList. 

https://www.patternfly.org/components/menus/menu#menuitem

**Comment by adamviktora** [comment] 2024-04-04 10:27
Noticing the same for Button props (https://www.patternfly.org/components/button#button)

**Comment by tlabaj** [comment] 2024-04-09 19:42
This is a duplicate of an issue in Org.  This needs to be fixed in the documentation-framework.  We have prioritizws it for the coming sprint
https://github.com/patternfly/patternfly-org/issues/3894

**Closed by tlabaj** 2024-04-09 19:42 UTC
Labels: bug
