### ISSUE TITLE
Make dropdown work to show itself

### ISSUE THREAD

**Issue by gitdallas** [patternfly/patternfly-react#7005] opened 2022-03-04 16:44 UTC
Currently, if the dropdown menu is in a position where it gets cut from overflow or edge of screen, it might not all be visible.

The popover has the ability to move itself around when this happens. It would be nice if the dropdown menu also had this ability.

**Comment by nicolethoen** [comment] 2022-05-10 17:34
This is a duplicate of https://github.com/patternfly/patternfly-react/issues/7286

**Closed by nicolethoen** 2022-05-10 17:34 UTC
Labels: enhancement :rocket:, wontfix
