### ISSUE TITLE
Resizable drawer: splitter disappears after resize to 0 width then toggling drawer

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#5280] opened 2020-12-18 20:30 UTC
Resize down to 0 width, then toggle drawer open / closed or resize the parent container, the splitter disappears.

**Comment by kmcfaul** [comment] 2021-01-07 17:01
The splitter isn't disappearing, it's being scrolled out of view. From what I can tell, when the content of the panel is wider/taller than the panel size, it scrolls to the content when re-toggled because the content receives focus.

@mcoker I'm not sure it's possible, but do you happen to know if this scrolling can be stopped?

Setting `minSize` to something larger would resolve the issue, so maybe instead of defaulting to 0 we should default to 25% (the smallest width available of the `widths` prop? Or I can keep the panel content hidden when the width is small (maybe lower than 5%, or through a new property). Would that be preferable or is raising the minSize enough? @evwilkin

**Comment by kmcfaul** [comment] 2021-01-13 15:40
@mcoker I think you mentioned a PR on the core side that would address this?

**Comment by mcoker** [comment] 2021-01-13 15:45
@kmcfaul yep, it's https://github.com/patternfly/patternfly/pull/3778 - @DaoDaoNoCode is working on it and it should be merged soon.

**Comment by kmcfaul** [comment] 2021-01-19 16:52
This is also being caused by our examples, which manually focus the panel content on expansion. I added to the min/max drawer size PR to address this (by giving the panels a minimum size where the focus doesn't scroll the panel).

**Comment by kmcfaul** [comment] 2021-01-25 15:53
Closed by #5313

**Closed by kmcfaul** 2021-01-25 15:53 UTC
