### ISSUE TITLE
Bug - [Alert] - [default variant should be ported to custom in the documentation examples]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#8973] opened 2023-04-19 10:20 UTC
**Describe the problem**
in Alert the PF css repo removed the styling for the default variant. They renamed it to custom.

We need to do the porting of the  examples to custom, otherwise there are examples of alerts without styles applied.

**How do you reproduce the problem?**[

https://patternfly-react-v5.surge.sh/components/alert/#inline-alerts-variants

**Expected behavior**

The  cyan background that appears in the html docs, should be also be in the react docs. https://pf5.patternfly.org/components/alert/

**Is this issue blocking you?**
wa is to manually apply the pf-m-custom class.
 
**What is your product and what release date are you targeting?**
Cockpit

**Comment by nicolethoen** [comment] 2023-04-19 13:16
I think this is a duplicate of this issue: https://github.com/patternfly/patternfly-react/issues/8775

**Comment by nicolethoen** [comment] 2023-04-25 20:14
closed in favor of: https://github.com/patternfly/patternfly-react/issues/8775

**Closed as completed by nicolethoen** 2023-04-25 20:14 UTC
Labels: PF5
