### ISSUE TITLE
Broken link in readme.

### ISSUE THREAD

**Issue by dhilst** [patternfly/patternfly-react#367] opened 2018-05-28 16:19 UTC
There is a broken link in the README.md

> As an alernative to consuming the patternfly-react.css file (found in dist/css), you can build patternfly-react styles into your css by including the Sass partials from dist/sass. The partial _patternfly-react.scss will pull in all the partials required for the patternfly-react components. When using the patternfly-react Sass files, you MUST include bootstrap and patternfly variables and mixins. An example of the required imports can be found in [patternfly-react.scss](https://github.com/patternfly/patternfly-react/blob/master/sass/patternfly-react.scss).

[patternfly-react.scss](https://github.com/patternfly/patternfly-react/blob/master/sass/patternfly-react.scss) leads to 404 page on github.

Regards,

**Comment by jeff-phillips-18** [comment] 2018-05-29 12:32
Duplicate of #366

**Closed by jeff-phillips-18** 2018-05-29 12:32 UTC
