### ISSUE TITLE
Using a empty string as a SelectOption with SelectVariant.typeahead crashes

### ISSUE THREAD

**Issue by mvollmer** [patternfly/patternfly-react#4361] opened 2020-06-09 15:21 UTC
@patternfly/react-core 3.158.1

This crashes when you start interacting with the Select component: https://codesandbox.io/s/green-water-3vl2t

On Firefox the error is `this.getDisplay(...) is undefined`.

It's the typeahead example from here https://www.patternfly.org/v4/documentation/react/components/select with an extra `{ value: '' }` entry in `options`.

Empty strings are not really useful as select options, but they should at least not crash the component, IMO. They could be filtered out, maybe.

**Comment by mvollmer** [comment] 2020-06-09 15:23
In case the codesandbox link stops working:

```
import ReactDOM from "react-dom";
import "@patternfly/react-core/dist/styles/base.css";
import "./fonts.css";

import React from "react";
import {
  Checkbox,
  Select,
  SelectOption,
  SelectVariant
} from "@patternfly/react-core";

class TypeaheadSelectInput extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      options: [
        { value: "Alabama" },
        { value: "Florida" },
        { value: "New Jersey" },
        { value: "New Mexico" },
        { value: "New York" },
        { value: "North Carolina" },
        { value: "" }
      ],
      isOpen: false,
      selected: null,
      isDisabled: false,
      isCreatable: false,
      hasOnCreateOption: false
    };

    this.onToggle = isOpen => {
      this.setState({
        isOpen
      });
    };

    this.onSelect = (event, selection, isPlaceholder) => {
      if (isPlaceholder) this.clearSelection();
      else {
        this.setState({
          selected: selection,
          isOpen: false
        });
        console.log("selected:", selection);
      }
    };

    this.onCreateOption = newValue => {
      this.setState({
        options: [...this.state.options, { value: newValue }]
      });
    };

    this.clearSelection = () => {
      this.setState({
        selected: null,
        isOpen: false
      });
    };

    this.toggleDisabled = checked => {
      this.setState({
        isDisabled: checked
      });
    };

    this.toggleCreatable = checked => {
      this.setState({
        isCreatable: checked
      });
    };

    this.toggleCreateNew = checked => {
      this.setState({
        hasOnCreateOption: checked
      });
    };
  }

  render() {
    const {
      isOpen,
      selected,
      isDisabled,
      isCreatable,
      hasOnCreateOption,
      options
    } = this.state;
    const titleId = "typeahead-select-id-1";
    return (
      <div>
        <span id={titleId} hidden>
          Select a state
        </span>
        <Select
          variant={SelectVariant.typeahead}
          typeAheadAriaLabel="Select a state"
          onToggle={this.onToggle}
          onSelect={this.onSelect}
          onClear={this.clearSelection}
          selections={selected}
          isOpen={isOpen}
          aria-labelledby={titleId}
          placeholderText="Select a state"
          isDisabled={isDisabled}
          isCreatable={isCreatable}
          onCreateOption={
            (hasOnCreateOption && this.onCreateOption) || undefined
          }
        >
          {options.map((option, index) => (
            <SelectOption
              isDisabled={option.disabled}
              key={index}
              value={option.value}
            />
          ))}
        </Select>
        <Checkbox
          label="isDisabled"
          isChecked={this.state.isDisabled}
          onChange={this.toggleDisabled}
          aria-label="toggle disabled checkbox"
          id="toggle-disabled-typeahead"
          name="toggle-disabled-typeahead"
        />
        <Checkbox
          label="isCreatable"
          isChecked={this.state.isCreatable}
          onChange={this.toggleCreatable}
          aria-label="toggle creatable checkbox"
          id="toggle-creatable-typeahead"
          name="toggle-creatable-typeahead"
        />
        <Checkbox
          label="onCreateOption"
          isChecked={this.state.hasOnCreateOption}
          onChange={this.toggleCreateNew}
          aria-label="toggle new checkbox"
          id="toggle-new-typeahead"
          name="toggle-new-typeahead"
        />
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<TypeaheadSelectInput />, rootElement);
```

**Comment by kmcfaul** [comment] 2020-06-11 17:16
The codesandbox doesn't crash for me in Chrome or FF. Do you still have the issue if you update the `@patternfly/react-core` to the latest version (4.18.5+)?

**Comment by rkaw92** [comment] 2021-02-10 10:29
Hey, can I please request re-opening this? The codesandbox definitely does crash, and I'm able to reproduce this today with `4.18.5` as well as `4.90.2`.

Below is a good case where:
* The bug prevents the user from using the typeahead feature (throws an error when user types stuff)
* The presence of an empty option might be useful because it has a distinct meaning

https://codesandbox.io/s/hardcore-grass-pkn18?file=/src/App.js

**Comment by KKoukiou** [comment] 2021-02-11 11:56
I can reproduce on the docs page with Release 2021.01

**Comment by KKoukiou** [comment] 2021-02-17 14:59
See https://github.com/patternfly/patternfly-react/pull/5450#issuecomment-780590280

**Comment by KKoukiou** [comment] 2021-06-01 15:44
It's a crash and should be fixed. still relevant.

**Closed** 2021-08-14 16:55 UTC
Labels: wontfix
