### ISSUE TITLE
Navigation doesn't keep state

### ISSUE THREAD

**Issue by quarckster** [patternfly/patternfly-react#1305] opened 2019-02-01 14:37 UTC
1. Go to http://patternfly-react.surge.sh/patternfly-4/components/nav
2. Scroll down to `Nav Mixed`
3. Click `Link 3 - expandable` and then `Link1`

Actual result:
The page reloads and Navigation state is reset.

Expected result:
Navigation should keep its state after clicking.

**Comment by tlabaj** [comment] 2019-02-04 19:42
Closing this issue because it is a duplicate of issue #1263

**Closed by tlabaj** 2019-02-04 19:42 UTC
Labels: PF4
