### ISSUE TITLE
Bug - Select - maxHeight

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#10024] opened 2024-01-19 14:44 UTC
The v4 `Select` supported a `maxHeight` property; however, it has been omitted for v5. The `popperProps` property supports `maxWidth`, but not `maxHeight`.

We've been using `maxHeight` in Cost Management to ensure all options fit within our wizard body. Otherwise, some options are cut off, appearing under the wizard's header. We need to limit the height of the `Select` list, so users can view all options.

**Cost Management with hidden options; AUD, CAD, CHF, CNY, and DKK**

![Screenshot 2024-01-19 at 9 26 37 AM](https://github.com/patternfly/patternfly-react/assets/17481322/a7897f50-a646-41ab-8d6a-9dda7a79ba77)

**Cost Management with `maxHeight`**

![Screenshot 2024-01-19 at 9 25 00 AM](https://github.com/patternfly/patternfly-react/assets/17481322/4b5a8403-83f7-403a-a7bd-b43d60e38198)

**Comment by tlabaj** [comment] 2024-01-31 16:52
Closing this as duplicate of #9847

**Closed by tlabaj** 2024-01-31 16:52 UTC
Labels: bug
