### ISSUE TITLE
Epandable Nav: pf4 expandable nav doesn't allow menu expansion by clicking on arrow

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4232] opened 2020-05-11 04:57 UTC
**Describe the issue. What is the expected and unexpected behavior?**
When testing the expandable nav component in the pf4 demo, the menu doesn't expand when you click on the right arrow. You have to move off and click elsewhere in the menu item.

**Comment by michpetrov** [comment] 2020-05-12 15:14
https://www.patternfly.org/v4/documentation/react/components/nav#expandable

This demo? It seem to work fine.

**Comment by tlabaj** [comment] 2020-05-19 13:12
@jcaianirh can you please link the demo that you see the issue in.

**Comment by jcaianirh** [comment] 2020-05-19 15:08
This is where I was looking: https://patternfly-react-master.surge.sh/documentation/react/demos/pagelayout/expandable-nav

**Comment by michpetrov** [comment] 2020-05-19 17:30
Okay, I can see the problem now. The demo hasn't caught up yet.

The issue is in CSS - previously the `.pf-c-nav__toggle` had `pointer-events: none;` but currently there are `.pf-c-nav__toggle`  and `.pf-c-nav__toggle-icon` neither of which have this rule; 

#4255 introduced a change to the layout and I assume the CSS as well but I don't know where the CSS comes from

**Comment by tlabaj** [comment] 2020-06-03 16:53
@jcaianirh  I don't see this issue in the demo
https://patternfly-react.surge.sh/documentation/react/demos/pagelayout/expandable-nav
I think we can close this one.

**Comment by jcaianirh** [comment] 2020-06-03 19:57
@tlabaj its still exists in the link i provided. how is it different from the link you provided? if thats no longer relevant then it can be closed.

**Closed** 2020-06-03 20:37 UTC
