### ISSUE TITLE
0 or negative number of items for pagination

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#2557] opened 2019-07-22 12:05 UTC
When consumer passes 0 or negative number to pagination user is still able to change page and can see 1 page out of 0.

![Screenshot from 2019-07-22 14-05-25](https://user-images.githubusercontent.com/3439771/61631108-c9f0a880-ac89-11e9-99f2-713806f1f356.png)

**Comment by tlabaj** [comment] 2019-07-22 21:57
@mcarrano isn't this a duplicate of #1949 that was closed?

**Comment by mcarrano** [comment] 2019-07-22 22:02
Well, sort of, @tlabaj . I guess technically it's a bug that the user can advance the page, but this should never happen as we should not be exposing a pagination control for 0 pages.

**Comment by rachael-phillips** [comment] 2019-07-23 17:56
@karelhala do you have any questions about @mcarrano 's comment above? I think his point of view is correct, that we shouldn't be exposing the control for 0 pages.

**Comment by karelhala** [comment] 2019-07-23 18:02
@rachael-phillips honestly I think that we should try to be as defensive as possible = Expect the unexpected. This is not a big of a change and it only disables both navigation elements if there are 0 items (similiar to when there is only one page).

On other hand we can change it and when user passes 0 items we can disable all navigational elements so there would be no page navigation and input would be disabled. If that is prefered way I can update linked PR.

**Comment by rachael-phillips** [comment] 2019-07-23 18:06
Thanks for the explanation @karelhala ! @mcarrano what is your preference for approach based on the design side?

**Comment by mcarrano** [comment] 2019-07-23 18:32
I think that @karelhala makes a good point about coding this to be as defensive as possible. If it's an easy fix, then I'd say to go forward with it. But from a usability perspective we should still be avoiding this situation.

**Closed** 2019-07-26 19:58 UTC
Labels: PF4, bug :bug:
