### ISSUE TITLE
Select, error while using with typeahead and custom objects

### ISSUE THREAD

**Issue by BhendiGawaar** [patternfly/patternfly-react#6183] opened 2021-08-18 07:20 UTC
**Describe the issue. What is the expected and unexpected behavior?**
 I recently upgraded to "@patternfly/react-core": "4.147.0". I am using Select with custom objects.
I get following error
```
TypeError: this.props.children is null
Select/this.componentDidUpdate
src/components/Select/Select.tsx:253
```
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
I am unable to reproduce this error in a sandbox

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
A Bug. Temporarily reverted back to the version 4.135.0 which I was using earlier where this works fine.

**What is your product and what release version are you targeting?**
NA

**Comment by tlabaj** [comment] 2021-10-01 20:48
@BhendiGawaar there were a number of changes to the Select in 4.147.0.  Are you able to reproduce with latest version so we can try on reproduce and address on our end?

**Comment by BhendiGawaar** [comment] 2021-10-04 11:22
I just tried with `4.157.3` and I am still able to reproduce the issue. Although this time error is slightly different
```Uncaught TypeError: prevProps.children is null
    componentDidUpdate Select.tsx:253```

**Comment by kmcfaul** [comment] 2021-11-15 15:16
@BhendiGawaar I am unable to reproduce this issue on our site, could you possibly link a codesandbox? 

There was also [PR merged](https://github.com/patternfly/patternfly-react/pull/6467) mid-October that fixes typeahead with custom objects when creating new options. Maybe updating again will pull in additional fixes.

**Closed** 2022-01-28 17:50 UTC
Labels: bug :bug:, wontfix
