### ISSUE TITLE
Convert Text Area to Typescript

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2210] opened 2019-06-11 13:58 UTC
Pulled from: https://docs.google.com/spreadsheets/d/1ykJC5WMmk9W9ICQ13TUqX0TTk9vuvse9TAq00DaHPYU/edit#gid=0

**Comment by tlabaj** [comment] 2019-06-20 17:22
Closing duplicate of #1953

**Closed by tlabaj** 2019-06-20 17:22 UTC
Labels: PF4
