### ISSUE TITLE
Bug - Select - Not showing SelectOptions if using inlineFilter and SelectOptions updated

### ISSUE THREAD

**Issue by jamestalton** [patternfly/patternfly-react#7757] opened 2022-07-27 15:46 UTC
**Describe the problem**
ACM is using the select component with an inlineFilter and async loading of the SelectOptions:
https://github.com/patternfly-labs/react-form-wizard/blob/main/src/inputs/WizAsyncSelect.tsx

Between @patternfly/react-core 4.221.3 and 4.224.1 the component broke because the SelectOptions stopped showing up.

If the inlineFilter is removed, the code works correctly.
The other work around is to open the Select twice and the second time it shows the SelectOptions.

**How do you reproduce the problem?**
~Provide steps to reproduce. A [codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f ) demonstrating the problem is appreciated.~

**Expected behavior**
The Select with inlineFilter should show SelectOptions that are async loaded.

**Is this issue blocking you?**
This is not blocking but ACM uses the PatternFly version provided by OCP.
If OCP uses this broken version of PatternFly it will severely affect our customers.
(Selecting a repo and opening the branches dropdown will not show any branches)

**Screenshots**
~If applicable, add screenshots to help explain the issue.~

**What is your environment?**
 - OS: OSX
 - Browser [e.g. chrome, safari]: Chrome

**What is your product and what release date are you targeting?**
ACM 2.6

**Any other information?**

**Comment by nicolethoen** [comment] 2022-07-27 16:56
I believe this was fixed with this PR: https://github.com/patternfly/patternfly-react/pull/7741
That will be included in the next release.

**Comment by tlabaj** [comment] 2022-09-23 18:38
@jamestalton can we close this one?

**Comment by jamestalton** [comment] 2022-09-27 15:10
@KevinFCormier does having a newer version of PatternFly fix this issue for ACM?
I believe this was seen in the ACM ArgoCD wizard.

**Comment by KevinFCormier** [comment] 2022-11-30 19:18
I have verified we don't see the bug on OCP 4.10 or 4.12, but 4.11 is using @patternfly/react-core@4.224.3

If I'm reading the tags correctly on the merge commit for that PR, the oldest version this is fixed in is @patternfly/react-core@4.225.0

Spinning up an OCP 4.11 instance, to confirm if I can reproduce there.

**Comment by KevinFCormier** [comment] 2022-11-30 22:39
I'm not able to reproduce on OCP 4.11 actually. The available options are changing reliably for me. Feel free to close.

**Closed** 2022-12-01 14:22 UTC
Labels: wontfix, bug, obsolete in pf5
