### ISSUE TITLE
Table with compound expansion

### ISSUE THREAD

**Issue by bclarhk** [patternfly/patternfly-react#1792] opened 2019-04-17 14:46 UTC
There is a design for Tables with compound expanding rows, but there is no react component for it. 
@rachael-phillips @LHinson @mcarrano 

We're using the compact expanding row in a modal for now, but compound would be a better solution.

**Comment by mcarrano** [comment] 2019-04-17 15:12
In discussing with @bclarhk this morning I see that we have the variant he needs in Core here: https://v2.patternfly.org/documentation/core/components/table#table-with-compound-expansion But looks like this never got carried over to the React implementation.

**Comment by dgutride** [comment] 2019-04-26 15:26
Thanks for the submission @bclarhk  - this appears to be a duplicate of https://github.com/patternfly/patternfly-react/issues/1325 - please reopen if it's not.

**Closed by dgutride** 2019-04-26 15:26 UTC
Labels: enhancement :rocket:
