### ISSUE TITLE
Bug - Dropdown/TextInput - Left/Right arrow keys do not work in text input inside a dropdown

### ISSUE THREAD

**Issue by ferhoyos** [patternfly/patternfly-react#9699] opened 2023-10-02 12:39 UTC
**Describe the problem**
I have a dropdown in my application with lots of dropdown options, so I have a text input inside the dropdown to be able to filter them. The filter works fine but the left/right arrow keys inside the text input do not move the text cursor along the input value.

![image](https://github.com/patternfly/patternfly-react/assets/122779323/822d9503-cbf5-4461-afe6-8c0459d5a6b3)

The dropdown component is the new PF5 one. The same text input inside the deprecated Dropdown component does not have this issue.

**How do you reproduce the problem?**
Here is a [codesandox](https://codesandbox.io/s/cold-forest-gtjr8l?file=/index.tsx) that adds a text input to basic Dropdown component from Patternfly examples (https://www.patternfly.org/components/menus/dropdown). 
1. Open the dropdown
2. Type something in the text input (first element with placeholder 'Filter by Name')
3. Press left/right arrow keys, nothing happens

**Expected behavior**
Inside the text input, pressing left/right arrow keys should move the text cursor along the input value.

**Is this issue blocking you?**
No, this is a minor issue since the filtering is working fine.

**Screenshots**
See the description and the code sandbox.

**What is your environment?**
 - OS: RHEL 8.7 CSB
 - Browse: Chrome
 - Version: 115.0.5790.170

**What is your product and what release date are you targeting?**
[Kiali](https://github.com/kiali/kiali)

**Any other information?**

**Comment by nicolethoen** [comment] 2023-10-02 15:07
I think this is a duplicate of: https://github.com/patternfly/patternfly-react/issues/9404

**Comment by ferhoyos** [comment] 2023-10-02 15:28
Yes, it seems so. I have not tested on Select, but it is likely the same issue (the left/right arrow keys are captured even when the input field still has focus preventing a user from pressing the left arrow back in the entered text).

**Comment by wise-king-sullyman** [comment] 2023-10-06 15:18
Closing as it appears this is a duplicate issue and that issue is being worked on this sprint.

Thanks for taking the time to make this, and if in our next release this issue isn't resolved for you please re-open this issue 🙂

**Closed by wise-king-sullyman** 2023-10-06 15:18 UTC
Labels: bug
