### ISSUE TITLE
PF4 - Calendar Month: Possible bug on generated aria-labels for the adjacent month days

### ISSUE THREAD

**Issue by carlosga** [patternfly/patternfly-react#6208] opened 2021-08-20 17:16 UTC
**Describe the issue. What is the expected and unexpected behavior?**

Possible bug on the generated aria-labels for the adjacent month days, the issue can be seen on the [calendar month demo page](https://www.patternfly.org/v4/components/calendar-month), inspecting the calendar september days shows that the aria labels are being generated with **August** as month, for example september 1 is being generated as:

```html
<td class="pf-c-calendar-month__dates-cell pf-m-adjacent-month">
  <button class="pf-c-calendar-month__date" type="button" tabindex="-1" aria-label="1 August 2021">1</button>
</td>
```
The aria-label being generated is: **1 August 2021**

Thanks in advance.

**Comment by redallen** [comment] 2021-08-20 17:20
Duplicate of #5988.

Please reopen if you find a way to get the screenreader to read this incorrect date.

**Closed by redallen** 2021-08-20 17:20 UTC
