### ISSUE TITLE
[Bug] [Select Component] @patternfly/react-core  2.11.1 

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#1764] opened 2019-04-15 06:52 UTC
Hi, in the version 2.11.1 there is a bug in the select component when try import badgeStyles

Trace
```bash
./node_modules/@patternfly/react-core/dist/esm/components/Select/Select.js
193:23-40 "export 'badge' (imported as 'badgeStyles') was not found in '../../@patternfly/patternfly/components/Badge/badge.css.js'
```

**Comment by aljesusg** [comment] 2019-04-15 06:52
cc @priley86

**Comment by redallen** [comment] 2019-04-15 13:36
Duplicate of #1711

**Closed by redallen** 2019-04-15 13:36 UTC
