### ISSUE TITLE
Bug - [Card] - controlling card selection with `isSelected` prop doesn't work as expected

### ISSUE THREAD

**Issue by amirfefer** [patternfly/patternfly-react#10136] opened 2024-03-07 13:29 UTC
**Describe the problem**
Controlling a clickable card and with the `isSelected` prop for reseting selection from a state, seems not to work.

**How do you reproduce the problem?**
Click on a clickable card, control the `isSelected` and try to reset it from a state - code example [codesandbox](https://codesandbox.io/p/sandbox/pf-card-bug-fqp8ln?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clth7xktg00063d5vqs9040gd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clth7xktg00023d5vi2svq0z4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clth7xktg00033d5vbw2eqh5r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clth7xktg00053d5vbmrzy4ef%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clth9c8kv00a23d5vklo1fe2o%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clth9cam900c43d5vdtbs46y3%2522%257D%255D%252C%2522sizes%2522%253A%255B33.333333333333336%252C33.333333333333336%252C33.333333333333336%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clth7xktg00023d5vi2svq0z4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth7xktg00013d5v9fjfxwqu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A13%257D%255D%257D%255D%252C%2522id%2522%253A%2522clth7xktg00023d5vi2svq0z4%2522%252C%2522activeTabId%2522%253A%2522clth7xktg00013d5v9fjfxwqu%2522%257D%252C%2522clth7xktg00053d5vbmrzy4ef%2522%253A%257B%2522id%2522%253A%2522clth7xktg00053d5vbmrzy4ef%2522%252C%2522activeTabId%2522%253A%2522clth93b6o001h3d5vlx7egfjb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clth93b6o001h3d5vlx7egfjb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clth7xktg00033d5vbw2eqh5r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clth7xktg00033d5vbw2eqh5r%2522%257D%252C%2522clth9c8kv00a23d5vklo1fe2o%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth941gw001d3d5v9xhfumr9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clth9c8kv00a23d5vklo1fe2o%2522%252C%2522activeTabId%2522%253A%2522clth941gw001d3d5v9xhfumr9%2522%257D%252C%2522clth9cam900c43d5vdtbs46y3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth9c91100bz3d5vuf68175z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clth9cam900c43d5vdtbs46y3%2522%252C%2522activeTabId%2522%253A%2522clth9c91100bz3d5vuf68175z%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D ) demonstrating the problem is appreciated.

**Expected behavior**
When `isSelected` is false, the card shouldn't render a selected style

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**

https://github.com/patternfly/patternfly-react/assets/11807069/4a4fcaf5-b073-4779-9150-526d316a8787

**Comment by ezr-ondrej** [comment] 2024-03-07 14:17
Migth be duplicate of https://github.com/patternfly/patternfly-react/issues/9875

**Comment by srambach** [comment] 2024-03-22 15:54
Closed as duplicate

**Closed by srambach** 2024-03-22 15:54 UTC
Labels: bug
