### ISSUE TITLE
PF4 dropdown onToggle event

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1022] opened 2018-12-07 04:12 UTC
I'm having an issue with PF4 events in the Koku UI/Insights platform; in particular, with the PF4 dropdown toggle. 

When I have more than one PF4 dropdown component in the same page, and I click on the first menu to expand, I noticed that my onToggle function for the second menu is called. The argument provided to my second onToggle function is false, so the menu does not expand; however, this should not be called at all IMO. The functionality appears to behave as if both components have the same parentRef?

**Comment by jiridostal** [comment] 2018-12-10 14:52
I'm experiencing exactly the same behavior. I did not figure out how to use multiple dropdowns on one page.

**Comment by dlabrecq** [comment] 2018-12-12 19:16
I've included a video/gif demonstrating that clicking on the "Group By" dropdown toggle invokes the handleSortByToggle function of my "Sort By" dropdown toggle.

![dropdowns](https://user-images.githubusercontent.com/17481322/49892994-64495d80-fe18-11e8-8c90-2398bee42d60.gif)

My first "Group By" dropdown can be found here: 
https://github.com/project-koku/koku-ui/blob/master/src/pages/ocpDetails/ocpDetails.tsx#L350

The second "Sort By" dropdown is located here: 
https://github.com/project-koku/koku-ui/blob/master/src/pages/ocpDetails/detailsToolbar.tsx#L250

**Comment by dlabaj** [comment] 2019-03-17 15:48
@dlabrecq I can't reproduce this with the PF4 Seed app https://github.com/dlabaj/patternfly-react-seed/tree/issue_1022 Is this still a problem?  If so can you update the seed app to reproduce this.

**Comment by dlabrecq** [comment] 2019-03-18 00:59
I've replaced the PF4 dropdown while introducing the PF4 table sort. Thus, we no longer have multiple dropdowns on the same page. Unfortunately, I don't have time to recreate the previous page.

Perhaps @jiridostal can confirm if this is still an issue?

**Comment by dlabaj** [comment] 2019-03-18 14:41
@dlabrecq No worries.  If @jiridostal can reproduce it with the app above let me know.

**Comment by dlabaj** [comment] 2019-03-21 12:48
Closing since we are unable to reproduce.

**Closed by dlabaj** 2019-03-21 12:48 UTC
Labels: PF4, bug :bug:, on hold, p1
