### ISSUE TITLE
PF4: Dropdown is missing prop documentation

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2885] opened 2019-09-09 11:29 UTC
At the moment, going to [Dropdown's documentation](https://www.patternfly.org/v4/documentation/react/components/dropdown/) you will not see the documentation for the Dropdown component, only it's siblings.

**Comment by tlabaj** [comment] 2019-09-09 19:57
Closing this since it is . duplicate of #2871

**Closed by tlabaj** 2019-09-09 19:57 UTC
Labels: bug :bug:, documentation :memo:
