### ISSUE TITLE
Indistinct syntax markup

### ISSUE THREAD

**Issue by andyvesel** [patternfly/patternfly-react#1787] opened 2019-04-17 11:41 UTC
On http://patternfly-react.surge.sh, the code syntax marked up with pale (e.g. grey) colors on a white background (see attach). It feels a bit inconvenient to read markup like this, especially when you have to learn those docs quite a while.
![syntax](https://user-images.githubusercontent.com/8054645/56284722-a4e21c00-6115-11e9-97b6-0f4236f96806.png)

**Comment by tlabaj** [comment] 2019-04-17 14:12
closing this since it is duplicate of Duplicate of #1724

cc @redallen

**Closed by tlabaj** 2019-04-17 14:12 UTC
