### ISSUE TITLE
Update keyboard interaction for pagination

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#3212] opened 2019-10-25 16:21 UTC
Update the pagination component based on the keyboard interaction [epic](https://github.com/patternfly/patternfly-react/issues/3108), use the [design documentation](https://docs.google.com/document/d/1m9nICFRgCXnXeHYN487BMX9MHw4DjvOln2B5p8yJa70/edit#heading=h.bg94bjykerss) to ensure component meets requirements. 
(Uses dropdown and will likely be impacted by Dropdown updates.)

Write integration tests to prevent keyboard interaction regressions.

**Comment by nicolethoen** [comment] 2022-09-23 15:47
This can be considered a duplicate of https://github.com/patternfly/patternfly-react/issues/6014 since all dropdown menus, including the Pagination menu, will use the same Menu component under the hood, they will be using the same interaction patterns.

**Closed by nicolethoen** 2022-09-23 15:47 UTC
Labels: accessibility
