### ISSUE TITLE
Bug - Popover - Translation is not behaving correctly (noticeable in datepicker)

### ISSUE THREAD

**Issue by rh-gvincent** [patternfly/patternfly-react#8445] opened 2022-12-14 16:34 UTC
**Describe the problem**
If you open the Calendar view by clicking multiple times on the calendar icon on the DatePicker component, you will see that the calendar popover position changes.

**How do you reproduce the problem?**

Go on https://www.patternfly.org/v4/components/date-picker/ an click multiple times on the calendar icon
See screenshot

**Expected behavior**
Popover position should not change

**Screenshots**

![Screen Recording 2022-12-14 at 17 28 20](https://user-images.githubusercontent.com/118891193/207653652-a64cc8ee-eddf-4f0c-9191-80a8ec90c89f.gif)

**What is your environment?**
 - OS: Os X
 - Browser Chrome
 - Version 108.0.5359.98 (Official Build) (x86_64)

**What is your product and what release date are you targeting?**

**Any other information?**

If you look at the style of the popover between click, you will see the translate3d values changing 

popover style on the first click: `opacity: 1; transition: opacity 300ms cubic-bezier(0.54, 1.5, 0.38, 1.11) 0s; position: absolute; inset: 0px auto auto 0px; z-index: 9999; transform: translate3d(217.5px, -152.5px, 0px);`
popover style on the second click: `opacity: 1; transition: opacity 300ms cubic-bezier(0.54, 1.5, 0.38, 1.11) 0s; position: absolute; inset: 0px auto auto 0px; transform: translate3d(0px, 61px, 0px); z-index: 9999;`
third: `opacity: 1; transition: opacity 300ms cubic-bezier(0.54, 1.5, 0.38, 1.11) 0s; position: absolute; inset: 0px auto auto 0px; transform: translate3d(217.5px, 0px, 0px); z-index: 9999;`
fourth: `opacity: 1; transition: opacity 300ms cubic-bezier(0.54, 1.5, 0.38, 1.11) 0s; position: absolute; inset: 0px auto auto 0px; transform: translate3d(0px, 61px, 0px); z-index: 9999;`

**Comment by nicolethoen** [comment] 2022-12-14 17:03
possibly the issue is coming from:
https://github.com/patternfly/patternfly-react/blob/9866c1a43993d32c3155dfa3851acabe9602c785/packages/react-core/src/helpers/Popper/thirdparty/popper-core/modifiers/computeStyles.ts#L69-L90

**Comment by tlabaj** [comment] 2024-11-21 16:08
This should be resolved in PF6 and PF5.

**Closed by tlabaj** 2024-11-21 16:08 UTC
Labels: Pinned
