### ISSUE TITLE
Create composable checkbox select demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6999] opened 2022-03-04 14:53 UTC
Follow up to https://github.com/patternfly/patternfly/pull/4696

**Comment by mcarrano** [comment] 2022-05-03 21:11
@tlabaj @nicolethoen should this have been added to a milestone? Seems like it got lost somehow.

**Comment by nicolethoen** [comment] 2022-05-10 17:31
This is a duplicate of https://github.com/patternfly/patternfly-react/issues/7367

**Closed by nicolethoen** 2022-05-10 17:31 UTC
