### ISSUE TITLE
PF4 Table: Expanded row issues

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1337] opened 2019-02-06 22:51 UTC
A couple issues with the PF4 table when rows are expanded:

1. All rows of the table are highlighted regardless what row is expended
2. Child toggle does not appear vertically centered
3. Arrows are always shown pointing down, regardless if the row is expanded

PF4 Table Example:
![chrome-capture](https://user-images.githubusercontent.com/17481322/52379101-740ba980-2a37-11e9-8190-b31df9e1b3b2.gif)

**Comment by karelhala** [comment] 2019-02-07 19:52
Thanks for opening this issue, all these are known and PRs are opened to fix them

> 1. All rows of the table are highlighted regardless what row is expended

https://github.com/patternfly/patternfly-react/pull/1313

> 2. Child toggle does not appear vertically centered

This is react-core issue, I have opened issue to be tracked there https://github.com/patternfly/patternfly-next/issues/1393

> 3. Arrows are always shown pointing down, regardless if the row is expanded

That happend after new version of core styles were released (before that chevrons were changing direction), but with new design we had to align to it by changing it in react. However that is also fixed in https://github.com/patternfly/patternfly-react/pull/1313

**Comment by mcarrano** [comment] 2019-02-07 19:53
@jgiardino and I have been looking at this implementation and are finding that this is not consistent with the design intent or what was implemented in Core. The intent is to just open a simple one-level expansion panel that is toggled by clicking the caret. See the Expandable Table example here: https://pf4.patternfly.org/components/Table/examples/

It looks like this was an attempt to implement something that works more like the Tree List we supported in PF3 (https://www.patternfly.org/pattern-library/content-views/tree-list-view/). I would consider this a different component that requires a new design story if we need to support it.

**Comment by dtaylor113** [comment] 2019-02-07 21:08
Fixed '#3 Arrows always pointing down'
Looking at other issues

**Comment by dlabrecq** [comment] 2019-02-08 01:47
FYI,  I encountered a slight variation when implementing my own table, where all rows are expanded at the same time. Although, the `onCollapse` even is only generated once.

![chrome-capture](https://user-images.githubusercontent.com/17481322/52454054-1c913a80-2b18-11e9-84f9-1c6fff285b47.gif)

**Comment by karelhala** [comment] 2019-02-08 07:06
I saw this before and it was caused by wrong implementation of `onCollapse` and parent reference. Is this code somehwere accessible? So I can check and see what is wrong.

**Comment by dlabrecq** [comment] 2019-02-08 07:26
I created a PR and the `onCollapse` can be found below.

https://github.com/project-koku/koku-ui/pull/466/files#diff-ebb4e1b5cb75f8809556d94f39e3bb9dR252

**Comment by karelhala** [comment] 2019-02-08 11:55
@dlabrecq as I suspected the parent calculation was not correct. I submitted review in your code to fix it.

**Comment by dlabrecq** [comment] 2019-02-09 00:26
Awesome. Thank you!

**Comment by karelhala** [comment] 2019-02-12 15:15
@dlabrecq all issues should be resoled, am I right?

**Comment by dlabrecq** [comment] 2019-02-12 15:21
I installed the prerelease version of the patternfly/react-* packages. I'm no longer seeing these issues. Feel free to close, unless you want me to confirm when patternfly beta is released?

**Comment by tlabaj** [comment] 2019-02-28 20:41
Closing this issue Based on discussion above.

**Closed by tlabaj** 2019-02-28 20:41 UTC
Labels: PF4, p1
