### ISSUE TITLE
Nav/Menu - consider decoupling Flyout logic

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#7709] opened 2022-07-18 14:22 UTC
**Is this a new component or an extension of an existing one?**
Nav/Menu

**Describe the feature**
Based on conversation in https://github.com/patternfly/patternfly-react/pull/7597, the logic for flyouts being decoupled (more similar to the DrilldownMenu) should be considered.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
N/A

**Any other information?**
N/A

**Comment by mcarrano** [comment] 2022-07-19 19:40
May be related to #7100

**Comment by mcarrano** [comment] 2022-09-19 15:13
We have #7100 in milestone 14. Should we close one of these as a duplicate @nicolethoen @tlabaj ?

**Comment by nicolethoen** [comment] 2022-09-19 15:25
Duplicate of https://github.com/patternfly/patternfly-react/issues/7100

**Closed as completed by nicolethoen** 2022-09-19 15:25 UTC
