### ISSUE TITLE
Incorrect PageSection code example in docs

### ISSUE THREAD

**Issue by jprosevear** [patternfly/patternfly-react#4518] opened 2020-07-13 01:10 UTC
**Describe the issue. What is the expected and unexpected behavior?**

Code example for https://www.patternfly.org/v4/documentation/react/components/page#main-section-padding is incorrect

```
<PageSection variant={PageSectionVariants.light} hasNoPadding>
          Section with no padding
</PageSection>
```
the hasNoPadding prop appears to be incorrect (not in the docs, guessing its legacy.

**Comment by KKoukiou** [comment] 2020-09-23 12:27
This is a duplicate of https://github.com/patternfly/patternfly-react/issues/4856

This one was created first but I already likned the issue above to the PR with the fix, this closing this as duplicate.

**Closed by KKoukiou** 2020-09-23 12:27 UTC
Labels: wontfix
