### ISSUE TITLE
SearchInput: Search & clear icons shifted to next line on input

### ISSUE THREAD

**Issue by rottencandy** [patternfly/patternfly-react#5416] opened 2021-02-04 16:28 UTC
**Describe the issue. What is the expected and unexpected behavior?**
The search icon & clear icon get snapped to next line on text input.
![temp](https://user-images.githubusercontent.com/20013884/106923291-ecdf9200-6733-11eb-8216-f33d8e1130c7.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Reproducible in Firefox 85 on release 2021.01 https://www.patternfly.org/v4/components/search-input

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug.

**Comment by redallen** [comment] 2021-02-05 15:58
Looks like we've missed the `<div class="pf-c-search-input__bar">`. I'll have a PR up shortly.

**Comment by joeldmyers** [comment] 2021-03-23 14:08
I am experiencing the same issue; I tried updating to the latest version and it seems that it is still showing the same bug.

**Comment by redallen** [comment] 2021-03-23 14:12
What version of `@patternfly/react-core` and Firefox are you using? All examples are working fine for me on `@patternfly/react-core@4.101.3` and Firefox 86.0.1:
![image](https://user-images.githubusercontent.com/47335686/112160046-2b37f000-8bc0-11eb-8a0c-3e262811e07d.png)

**Comment by joeldmyers** [comment] 2021-03-23 20:21
I think I have tracked down the issue for the case we're seeing.  The issue is a <SearchInput /> within a <Flex> component: 

https://codesandbox.io/s/fervent-minsky-dw26s?file=/index.js

https://dw26s.csb.app/ - demo here.  

For the SearchInput not inside a Flex, the X stays consistently within the original width of the input and is positioned correctly.

For the SearchInput inside a Flex, the X is positioned outside the original input, making the whole thing longer, which can result in unwanted behavior.  We have it within a table, which I think is what is causing that to break on a new line.  

LMK if you'd like me to close this and open a new issue specific to the Flex.  

Thanks!

**Comment by redallen** [comment] 2021-03-23 20:28
I'm unable to reproduce the flex problem in Firefox 86.0.1. Your demo looks like this:
![image](https://user-images.githubusercontent.com/47335686/112213547-91d70100-8bf4-11eb-89cf-0fd9c5f7cf45.png)

Once we get a reproduction we can keep it here if it's a React problem or move it to Core if it's a CSS problem.

**Comment by joeldmyers** [comment] 2021-03-23 20:31
Do you mind trying again? I just made a tweak in that sandbox.  Pay attention to the original width in the bottom one. I am also on FF 86.0.1 so it should be the same.

**Comment by redallen** [comment] 2021-03-23 20:36
I'm seeing this now, still no search icon & clear icon getting snapped:
![image](https://user-images.githubusercontent.com/47335686/112214614-c7c8b500-8bf5-11eb-8c76-469384710f38.png)

**Comment by joeldmyers** [comment] 2021-03-24 17:09
Ah, I was trying to point out that the width of the input itself was changing depending on the flex, thinking that that was causing the breakage we were seeing in a more complex table setup in our app.  However, after review, I believe this is expected behavior; I was able to pinpoint the issue as having to do with a webpack configuration issue, so I'll go ahead and close this issue again.  Thanks!

**Closed by joeldmyers** 2021-03-24 17:09 UTC
