### ISSUE TITLE
Text input group should allow for operators

### ISSUE THREAD

**Issue by zlayne** [patternfly/patternfly-react#7564] opened 2022-06-08 17:29 UTC
**Is this a new page or a change to an existing one?**
This is an enhancement request for the Text-Input-Group component. 

**Describe the enhancement**
Currently the Text-Input-Group component only allows for attribute-value pairing with `:` (ex: `Cluster:local-cluster`). This enhancement would allow for the use of the following operators: `=, <, <=, >, >=, !, !=` (ex: `cpu>75%`).

**Are there visuals for this enhancement? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by nicolethoen** [comment] 2022-06-21 17:17
Hello @zlayne Thanks so much for opening the issue.

I presume you were looking at this [attribute-value filtering demo](https://www.patternfly.org/v4/components/text-input-group/react-demos#attribute-value-filtering). Fortunately, the details of how the attribute/value filtering is implemented is incredibly flexible. It would require a lot of business logic implemented on your end - and that is by design, since we don't usually ship our components with implementation specific complex logic, since that becomes so difficult to maintain, especially as there is so much diversity of use cases and specifics for products.

The `:` delimiter in the attribute/value demo is appearing because of the logic on lines 114 and 120 of the `TS` code preview on the demo. That logic could be expanded so that the code can expect one of many delimiters or operators however your use case dictates. Hopefully that helps.

**Comment by nicolethoen** [comment] 2022-06-21 17:56
absolutely! 
I will close this issue for now - it can always be reopened if we want to readdress/reassess this conversation.

**Closed by nicolethoen** 2022-06-21 17:56 UTC
Labels: needs info
