### ISSUE TITLE
Link in react-icons readme 404's

### ISSUE THREAD

**Issue by mabashian** [patternfly/patternfly-react#4075] opened 2020-04-14 19:41 UTC
**Describe the issue. What is the expected and unexpected behavior?**

`PatternFly React Docs` link points to https://patternfly-react.surge.sh/patternfly-4/icons/ but I think it should point to https://patternfly-react.surge.sh/icons/

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Go to https://github.com/patternfly/patternfly-react/blob/master/packages/react-icons/README.md and click on the link that says `PatternFly React Docs`

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, I guess

**What is your product and what release version are you targeting?**

N/A

Screenshot:

<img width="1674" alt="Screen Shot 2020-04-14 at 3 38 21 PM" src="https://user-images.githubusercontent.com/9889020/79266995-68e7b100-7e66-11ea-9862-6a2d4fe52181.png">

**Comment by tlabaj** [comment] 2020-04-16 14:05
Hi @mabashian this is is a duplicate of #3936 and has been resolved so I am closing this issue.

**Closed by tlabaj** 2020-04-16 14:05 UTC
