### ISSUE TITLE
Clean up demos from latest core alpha bump

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#10238] opened 2024-04-02 18:04 UTC
- Ensure correct date props are being passed to the Timestamp components (so that the datetime attribute matches the visible text string that is rendered; this may require rendering 2 Timestamps such as the custom menu data select example where a date range is displayed)

- Ensure icons in the Card examples are using the color associated with the status

https://github.com/patternfly/patternfly-react/pull/10230#pullrequestreview-1974471415

**Comment by adamviktora** [comment] 2024-05-29 11:49
Closing as this is a duplicate of #10239.

**Closed by adamviktora** 2024-05-29 11:49 UTC
Labels: sm, Tech debt, PF6
