### ISSUE TITLE
Add <nav> version of tabs

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1597] opened 2019-03-18 17:56 UTC
We added an example of the tabs component using a `<nav>` element for both primary nav and secondary nav. When the tabs component uses `<nav>`, it needs an `aria-label` as covered in the [tabs using the nav element example](https://github.com/patternfly/patternfly-next/pull/1548/)

cc @jgiardino

**Comment by jgiardino** [comment] 2019-03-18 18:54
This is kind of a duplicate of #1268 (if you dig further down to look at https://github.com/patternfly/patternfly-next/issues/1328), but this issue is definitely more explicit about what updates are required.

@rebeccaalpert had done some work related to this in https://github.com/rebeccaalpert/patternfly-react/commit/5098c5303c2b163ac42140c8bd45a405f46846a9

Should we close this issue or keep it open and assign to @rebeccaalpert?

**Comment by mcoker** [comment] 2019-03-18 20:45
Ah, thanks @jgiardino. Looking at https://github.com/patternfly/patternfly-react/pull/1413, I think the only thing needed in that PR is an example of the secondary tabs in a `<nav>` element (maybe we don't need that as an example?) and to update the `aria-label`  on primary tabs to `Local` and `Local secondary` on secondary tabs. I can leave that comment on #1413 and close this issue, or you can add this issue to #1413's description and take care of it. What do you prefer @rebeccaalpert ?

**Comment by rebeccaalpert** [comment] 2019-03-18 20:56
@mcoker - Should the aria-label be "Local"/"Local secondary" on all primary/secondary Tabs or just `<nav>` Tabs?

I can add this issue to #1413's description and take care of it.

**Comment by mcoker** [comment] 2019-03-18 20:59
Just `<nav>` tabs. non-`<nav>` tabs shouldn't have an `aria-label`. Thanks!!

**Comment by jgiardino** [comment] 2019-03-18 21:09
+1 on updating the examples to show the text strings we recommend for these cases

**Comment by rebeccaalpert** [comment] 2019-03-18 21:23
I added the secondary Tabs example and updated the aria-labels in https://github.com/patternfly/patternfly-react/pull/1413. (See the latest commit.) Let me know in that PR if that works or not.

**Closed** 2019-04-02 17:52 UTC
Labels: PF4, p1
