### ISSUE TITLE
Bug - v5 alpha testing - Select options appear ouside wizard modal

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9233] opened 2023-06-02 19:45 UTC
While testing the Cost management UI, we encountered the following issue with the Select options appearing outside the wizard modal.

**Before**
![Screenshot 2023-06-02 at 3 42 35 PM](https://github.com/patternfly/patternfly-react/assets/17481322/310a24ca-c71f-446b-9903-c5628a35143e)

**After**
![Screenshot 2023-06-02 at 3 41 44 PM](https://github.com/patternfly/patternfly-react/assets/17481322/aaaf3fbf-c416-4231-ae39-4ae1647f9fa1)

**Code**
![Screenshot 2023-06-02 at 3 43 59 PM](https://github.com/patternfly/patternfly-react/assets/17481322/178cd43e-a8de-455c-b644-f75cf62af698)

**Comment by tlabaj** [comment] 2023-06-05 13:40
@dlabrecq was this working with the last round of alpha testing?

**Comment by tlabaj** [comment] 2023-06-05 13:44
@mcoker could this be a css issue?

**Comment by gitdallas** [comment] 2023-06-05 15:18
@tlabaj - i first noticed this in april https://docs.google.com/document/d/1bQmzy4nRdNZqvFRha0cOr0hiB8JRYZfnYpz3nz3Z_SI/edit#heading=h.rqz5lgwh6tbq

**Comment by gitdallas** [comment] 2023-06-05 16:39
@tlabaj html: 
![image](https://github.com/patternfly/patternfly-react/assets/5322142/4a95c9a0-57dd-4de4-9ca1-8ced67972329)

**Comment by mcoker** [comment] 2023-06-05 18:59
@tlabaj it looks like it is a CSS issue that isn't working well with the popper styles we updated recently to use `min-width` instead of `width`.

We apply the CSS `width: 100%` to the select component in core, and popper is applying `min-width: {{width of select toggle}}` to the select when it wraps the menu, and `width: 100%` is overriding the `min-width`. When the popper used to apply `width`, popper's width would override the CSS width.

I think a good fix for this could be to apply `width: auto` to the select that wraps the select menu when popper controls it. So that element would have now `width: auto; min-width: {{width of toggle}}` - is that something we can do?

**Comment by tlabaj** [comment] 2023-06-05 20:28
@mcoker yes, we should be able to make that change

**Comment by dlabrecq** [comment] 2023-06-07 15:53
I've tested 5.0.0-prerelease.3 and still see the issue

**Comment by thatblindgeye** [comment] 2023-06-08 18:19
Speaking with @dlabrecq it looks like the issue was that the original fix is in one of our `5.0.0-prerelease` versions and not the latest alpha. Confirmed the fix works when using a prerelease version so will be closing this again.

**Closed by thatblindgeye** 2023-06-08 18:19 UTC
Labels: bug, needs triage, PF5
