### ISSUE TITLE
Bug - DragDrop - basic example isn't reordering

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#10038] opened 2024-01-23 21:23 UTC
The current/non-dndkit drag and drop isn't reordering in the basic example on a drop event. The multiple lists example does reorder when an item is dragged and dropped within the same list however, so it seems to be a state update that's not happening in the basic example.

**Comment by adamviktora** [comment] 2024-05-14 13:12
Closing as the issue is not occuring in the current version of main / v5 anymore.

**Closed by adamviktora** 2024-05-14 13:12 UTC
Labels: bug
