### ISSUE TITLE
Enhance Select component with big number of SelectOptions

### ISSUE THREAD

**Issue by carlosthe19916** [patternfly/patternfly-react#5393] opened 2021-01-28 10:36 UTC
**Describe the issue. What is the expected and unexpected behavior?**
- The [Select](https://www.patternfly.org/v4/components/select) component can overflow the whole page if the number of `SelectOption` inside the `Select` is big. Adding a scroll might help.
- When I open the dropdown, filter elements, and then select the element I HAVE TO DOUBLE CLICK in order to select the checkbox, a single click doesn't work. However, when the filter is not applied then a single click is enough to select an option.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

I'm attaching a video to quickly explain how to reproduce the issue.

https://user-images.githubusercontent.com/2582866/106125310-49ebae80-615c-11eb-9aba-01f2059b2c63.mp4

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a nice enhancement to have in Patternfly-react because sometimes the elements of the dropdown might come from a database and the size can easily exceed 20 (enough to overflow the page).

**What is your product and what release version are you targeting?**
Release 2020.16

**Comment by tlabaj** [comment] 2021-03-16 21:26
@carlosthe19916  for the first bullet point.  If you set `maxHeight` of the select, a scroll will be added.  
I am unable to reproduce the second bullet point.  Can you please provide further steps or a code sandbox to help us debug?

**Comment by carlosthe19916** [comment] 2021-03-18 17:27
@tlabaj I've tested the latest available version of @patternfly/react-core and it seems the second bug I reported is not there anymore and since `maxHeight` solves the first problem I'm happy to close this PR.

**Comment by tlabaj** [comment] 2021-03-25 14:21
Thank you for verifying this @carlosthe19916.  I am closing this issue.

**Closed by tlabaj** 2021-03-25 14:21 UTC
