### ISSUE TITLE
Wizard structure Issue

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2592] opened 2019-07-25 18:15 UTC
I wanted to break the master issue into separate issues to improve tracking. Referencing https://github.com/patternfly/patternfly-react/issues/2114

Structure
The structure of wizard is confusing:

<div>
  <WizardHeader />
  <WizardToggle >
     <WizardFooter />
  </WizardToggle>
</div>
Where is the body? Where is the nav? Why is the footer in the toggle?

The structure should be more clear and readable, something like this:

<WizzardWrapper>
  <WizardHeader />
  <WizardNav>
    <WizardNavItem />
     ...
  </WizardNav>
  <WizardBody>
     ...
  </WizardBody>
  <WizardFooter>
    ...
  </WizardFooter>
</WizzardWrapper>
A structure like this would allow all consumers to build their own implementations because...

Wizard is too controlled
In our project, we have a specific approach how to build and render forms (and wizard forms). However, our approach can't be adjusted to use how this component is designed. So, I had to implement my own Wizard PF4: https://github.com/data-driven-forms/react-forms/blob/b9bef870c4755a4436290df359a6a965f4c6236a/packages/pf4-component-mapper/src/form-fields/wizard/wizard.js

Individual parts of wizard should be self-contained. There could be a second Wizard component, which would be controlled by PatternFly, but there should be a set of basic components which provides styles and very basic render logic.

I would like to get WizardWrapper, WizardHeader, WizardNav, WizardNavItem, WizardBody, WizardFooter and build my own logic around it. (Because we are using Wizards in a specific way and I believe we are not the only ones.)

cc @tlabaj @rvsia

**Comment by boaz0** [comment] 2020-01-15 21:32
@rachael-phillips @tlabaj may I try my luck and help with this?
Thanks.

**Comment by rachael-phillips** [comment] 2020-01-16 18:54
HI @boaz0, this issue is not ready to be picked up yet. We need to make some architectural decisions first. Keep in touch here, and we'll see what the direction looks like!

**Comment by jschuler** [comment] 2020-02-19 20:22
Comment/question about the structure here
https://github.com/patternfly/patternfly-react/issues/2114#issuecomment-588430459

**Comment by tlabaj** [comment] 2020-02-20 15:50
This one is ready to be picked up.  See comments in #2114 (comment) for proposed solution.

**Comment by redallen** [comment] 2020-05-08 18:39
Duplicate of #2114.

**Closed by redallen** 2020-05-08 18:39 UTC
Labels: PF4, p2, pinned
