### ISSUE TITLE
Table Inline Edit Buttons are positioned incorrectly when used inside a Modal

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#535] opened 2018-08-15 16:59 UTC
In #534, I added a story to storybook to showcase this bug. When using the `TableInlineEditRow` on a table that is inside a Modal, the buttons appear to be positioned relative to the window, rather than relative to the table or the row. This leads to very broken-looking positioning:

With a large window:

![screenshot 2018-08-15 10 50 32](https://user-images.githubusercontent.com/811963/44158595-0cc1fd80-a083-11e8-8702-5323f047a965.png)

With a small window:

![screenshot 2018-08-15 11 59 23](https://user-images.githubusercontent.com/811963/44158615-1c414680-a083-11e8-834d-08d147cc8e9a.png)

The positioning is done with JavaScript here: https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-react/src/components/Table/TableInlineEditRow.js#L6

I think maybe this should be reimplemented in pure CSS, with `position: relative` on the row to make it the offset parent, and `position: absolute` with `right` and `top` on the buttons. This way, they would be positioned correctly regardless of the context, and we wouldn't have so much repositioning on window resize.

However, I'm not sure if maybe that was attempted first and this positioning was done with JS for a good reason, so I don't want to assume that a pure CSS positioning would be the right solution here. @tstrachota can you shed any light on this?

**Comment by michaelkro** [comment] 2018-08-16 13:40
The root cause of this issue is that the inline edit buttons use `position: fixed`.

It turns out that fixed positioning does behave as expected if any ancestor has `transform` set to anything other than none.  [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Fixed_positioning)

In our case, the `.modal-dialog` class used by our modals sets

```scss
transform: translate(0, 0)
```

and so, in this case, the button row treats this `div` as it's containing block, as opposed to the `viewport`, which is what the JS calculations are based upon

**Comment by mturley** [comment] 2019-04-18 15:29
I ended up solving this problem downstream by rendering the edit buttons as a child of the last table cell and using relative positioning, but it took a very confusing bit of `React.cloneElement` magic that is tightly coupled to the cell contents we have in our table: https://github.com/ManageIQ/manageiq-v2v/pull/941

Thought I'd leave that here as inspiration if anyone figures out how to solve the problem more generally.

**Comment by dgutride** [comment] 2019-06-11 14:27
Closing due to workaround - thanks @mturley

**Closed by dgutride** 2019-06-11 14:27 UTC

**Comment by mturley** [comment] 2019-06-11 14:44
This one is definitely still a bug, but maybe one that's not worth fixing. The workaround is pretty invasive.
