### ISSUE TITLE
Add new Toolbar component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1292] opened 2019-01-30 23:04 UTC
We removed the Toolbar layout and made a new component.

https://github.com/patternfly/patternfly-next/pull/1282

I'll also just note this comment in the description:

> when the user selects ascending vs descending the icon will have to switch from sort-amount-up to sort-amount-down

**Comment by dlabaj** [comment] 2019-02-26 16:31
Duplicate of #919

**Closed by dlabaj** 2019-02-26 16:31 UTC
Labels: PF4, p1
