### ISSUE TITLE
Bug - Tooltips on Charts - Tooltips on charts are cut off close the edge of the page

### ISSUE THREAD

**Issue by sjd78** [patternfly/patternfly-react#7922] opened 2022-09-01 18:35 UTC
**Describe the problem**
When using Tooltip on Charts, if the chart is close to the edge of the page and the tooltip is wide enough, the edge of the tooltip is cut off from view.  Normal Tooltips would be able to change render location to remain visible.  Tooltips on charts should do the same.

**How do you reproduce the problem?**
Put a chart close the edge of a page and include wide tooltips.  Using a time series with a sparkline (`ChartArea`) chart is our main use case.

See https://issues.redhat.com/browse/RHV-21535

This is the use of the `ChartArea` component in the application: https://github.com/oVirt/ovirt-engine-ui-extensions/blob/master/src/components/patternfly/AreaChart.js

**Expected behavior**
Expect the chart tooltip to act like standard tooltips and to shift orientation to be completely visible on the page.

**Is this issue blocking you?**
There is no workaround.

**Screenshots**
From the issue linked above:
![dHpykiz](https://user-images.githubusercontent.com/3985964/187986594-c2f15f08-862f-4d28-98e0-9f8d0dddbf1d.png)

**What is your environment?**
 - OS: Any
 - Browser: Any
 - Version: "@patternfly/react-charts": "^6.74.3"

**What is your product and what release date are you targeting?**
oVirt

**Comment by tlabaj** [comment] 2022-09-02 13:20
cc @dlabrecq

**Comment by dlabrecq** [comment] 2022-09-02 22:58
You either need to provide a larger margin, greater chart padding, or use the `constrainToVisibleArea` property with `<ChartVoronoiContainer>`. This is demonstrated in nearly all chart examples.

See http://patternfly-react-main.surge.sh/charts/tooltips#voronoi-container

**Comment by sgratch** [comment] 2022-09-06 13:31
@sjd78 just to mention that this was also reproduced for us on oVirt VM portal with the the Donut chart  tooltips as well, but I can see that the `constrainToVisibleArea` property is relevant there too: https://www.patternfly.org/v4/charts/donut-chart/#chartdonut

**Comment by sjd78** [comment] 2022-09-06 15:30
The `constrainToVisibleArea` feature is frustrating to use at best.  When comparing normal tooltips to chart tooltips it is even more frustrating.

When `constrainToVisibleArea` is setup, the chart tooltips only display in the chart's render area.  Essentially for any charts that use the full chart render area, or have narrow margins (such as our chart's on oVirt Admin Console dashboard), the tooltips just cover the chart and make the whole thing annoying.  @sgratch , would reworking the layout (chart size, margins and probably relative locations) be a valid or feasable solution here?

If the chart tooltips behaved like regular tooltips and shifted their orientation based on view window edge proximity, the experience would be less frustrating.  That's the reason for this issue.

@dlabrecq: What is your suggestion if a higher density of charts on the page is required? Or worse, what to do if another language's tooltip take more space than what is designed for?

**Comment by dlabrecq** [comment] 2022-09-06 16:05
IMO, the best solution Victory has to offer is the `constrainToVisibleArea` feature. This approach ensures tooltip continues to be readable, despite the local's text length.
https://formidable.com/open-source/victory/docs/victory-tooltip#constraintovisiblearea

We have examples of tooltips that shift orientation, but vertical cursors do not apply to pie charts, unfortunately.
http://patternfly-react-main.surge.sh/charts/tooltips#embedded-html

In general pie charts need a bit more space to allow for tooltips, since tooltips are rendered as part of the SVG for Victory based components. However, there are some alternatives we've documented below.

For example, you could use the CSS overflow approach below. This allows the tooltip to overlap other areas of the page without being cut off.
http://patternfly-react-main.surge.sh/charts/tooltips#css-overflow

You may also wrap the chart in a PatternFly `Tooltip`. This would potentially display all tooltips in the same location (e.g., triggered by a shared event).
http://patternfly-react-main.surge.sh/charts/tooltips#wrapped-chart

**Comment by dlabrecq** [comment] 2022-09-06 16:32
IMO, the best solution Victory has to offer is the `constrainToVisibleArea` feature. This approach ensures tooltips continue to be readable, despite the locale's text length.
https://formidable.com/open-source/victory/docs/victory-tooltip#constraintovisiblearea

We have examples of tooltips (using vertical cursors) that shift orientation. This would work well with your area chart, but wouldn't apply to pie charts, unfortunately. 
http://patternfly-react-main.surge.sh/charts/tooltips#embedded-html

Victory typically places tooltips close to the pie segment they're related to; although, pie charts have props like  `labelPlacement` and `labelPosition` which may alter that. The tooltip component also has its own props like `orientation`, `pointerLength`, etc, which could be useful?

In general pie charts need a bit more space to allow for tooltips, which are rendered as part of the SVG for Victory based components. However, there are some alternatives documented below.

For example, you could use the CSS overflow approach below. This allows the tooltip to overlap other areas of the page without being cut off.
http://patternfly-react-main.surge.sh/charts/tooltips#css-overflow

You may also wrap the chart in a PatternFly `Tooltip`. This would potentially display all tooltips in the same location (e.g., triggered by a shared event).
http://patternfly-react-main.surge.sh/charts/tooltips#wrapped-chart

**Comment by dlabrecq** [comment] 2022-09-06 16:41
IMO, the best solution Victory has to offer for pie charts is the `constrainToVisibleArea` feature. This approach ensures tooltips continue to be readable, despite the locale's text length.
https://formidable.com/open-source/victory/docs/victory-tooltip#constraintovisiblearea

We have examples of tooltips (using vertical cursors) that shift orientation. This may work well with your area chart, but wouldn't apply to pie charts, unfortunately.

Basic: http://patternfly-react-main.surge.sh/charts/tooltips/#combined-cursor-and-voronoi-containers
Legend: http://patternfly-react-main.surge.sh/charts/tooltips#embedded-html

Victory typically places tooltips close to the pie segment they're related to; although, pie charts have props like  `labelPlacement` and `labelPosition` which may alter that. The tooltip component also has its own props like `orientation`, `pointerLength`, etc, which could be useful?

In general pie charts need a bit more space to allow for tooltips, which are rendered as part of the SVG for Victory based components. However, there are more alternatives documented below.

For example, you could use the CSS overflow approach below. This allows the tooltip to overlap other areas of the page without being cut off.
http://patternfly-react-main.surge.sh/charts/tooltips#css-overflow

You may also wrap the chart in a PatternFly `Tooltip`. This could display all tooltips in the same location (e.g., potentially triggered by a shared event).
http://patternfly-react-main.surge.sh/charts/tooltips#wrapped-chart

**Comment by mcarrano** [comment] 2022-10-11 19:18
@sjd78 does this address your issue? If so, I will close this out. Thanks.

**Comment by sjd78** [comment] 2022-10-11 20:31
> @sjd78 does this address your issue? If so, I will close this out. Thanks.

Honestly I tried a lot of different ways to handle the tooltips and nothing really came out as a consistently good way to handle things.  I ended up leaving the tooltips as they were, and let some of them get cut off at the edge of the window.  I didn't have any problems with tooltips getting cut off on page.

So I think it is ok to close this PR.

**Comment by mcarrano** [comment] 2022-10-11 21:11
@sjd78 thanks for getting back to me quickly. I will close then. Unfortunately this is one area where we are constrained by use of a 3rd party package.

**Closed by mcarrano** 2022-10-11 21:11 UTC
Labels: bug, needs info
