### ISSUE TITLE
Regression in local workspace development workflow/doc

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#3154] opened 2019-10-16 16:04 UTC
Some time ago, after starting the PF4 workspace with `yarn start:pf4`, we included output that confirmed the development server had started successfully and also a note about what url/port the server could be reached at.

At some point, months ago, this stopped working. Aside from it being a general regression of behavior in our development workflow, it also made me realize that we haven't documented this information anywhere else where users can find. Currently, the below snippet shows the last thing users are made aware of after running yarn start:pf4

`@patternfly/react-docs: atternfly/react-docs`

Notice it doesn't tell me the dev server has started (or not), it doesn't tell me what URL I can access the workspace from, and the `@p` was mangled in a previous linebreak.

The real problem is that if any ol' community member decides to pull the project locally and try to start it, they'll get to this point and likely not know what to do next. This means they need to reach out to someone (and have an exchange) before they can get up and running for the very first time.

Why did we remove these helpful and critical bits of information? Can we add them back?

**Comment by redallen** [comment] 2019-10-23 19:30
The regressions are because we got rid of streaming merged `stdout` from Lerna in favor of the cached block output for Node 8 compatibility for the incremental build. Gatsby's `stdout` gets lost in the mess.

In the meantime, we've agreed to just add a line to the Readme saying to go to http://localhost:8000

**Comment by tlabaj** [comment] 2019-12-02 19:37
closed by #3254

**Closed by tlabaj** 2019-12-02 19:37 UTC
Labels: PF4, documentation :memo:, infrastructure
