### ISSUE TITLE
Bug - Log viewer - Line numbers greater than 5 digits overlay divider and content

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#7876] opened 2022-08-22 15:43 UTC
**Describe the problem**
Line numbers greater than 5 digits overlay the divider and content.

**How do you reproduce the problem?**
See https://issues.redhat.com/browse/OCPBUGS-183

**Expected behavior**
Line numbers exceeding 5 digits in length should not overlay the divider and content.

**Is this issue blocking you?**
No.

**Screenshots**
Mocked the issue on https://www.patternfly.org/v4/extensions/log-viewer#with-search by editing the line number values using the browser's inspector.
<img width="452" alt="Screen Shot 2022-08-22 at 11 16 18 AM" src="https://user-images.githubusercontent.com/895728/185962235-bdddb688-3ec8-47dd-b2cb-dcdf54bb7246.png">

**What is your environment?**
 - OS: MacOS
 - Browser: Chome
 - Version: 104

**What is your product and what release date are you targeting?**

OpenShift

**Any other information?**

**Comment by nicolethoen** [comment] 2022-08-29 12:02
@mcoker @DaoDaoNoCode I think this will be fixed in the CSS

**Comment by mcoker** [comment] 2022-08-30 19:12
We have `--pf-c-log-viewer__index--Width` on the core side that sets the width of that left column. That could be dynamically updated to support the current number of lines.

**Comment by DaoDaoNoCode** [comment] 2022-08-31 14:16
I tried a lot of methods but it's proved that the issue is really tricky. The log viewer is virtualized, so everything is pre-calculated and estimated before the render so that's why it has a good performance. If we change the index width when you scroll the list, everything would be recalculated and it will trigger the re-render of the list, which will scroll back to the top of the log window.
I have a solution for this issue as a trade-off, we can create a prop named `initialIndexWidth`, if you anticipate your logs will be a very large amount, you can set the `initialIndexWidth` when you render the log viewer so it will give you a wider space for the indices. The only drawback of this method is there will be a little bit more room for the indices when they are small.
<img width="821" alt="Screen Shot 2022-08-31 at 10 13 53 AM" src="https://user-images.githubusercontent.com/37624318/187700164-4eddbca4-c442-4aff-8cb4-30b1d6771ba3.png">

@rhamilto Please let me know what you think and if you have any other ideas, thanks!

**Comment by rhamilto** [comment] 2022-08-31 14:45
> I tried a lot of methods but it's proved that the issue is really tricky. The log viewer is virtualized, so everything is pre-calculated and estimated before the render so that's why it has a good performance. If we change the index width when you scroll the list, everything would be recalculated and it will trigger the re-render of the list, which will scroll back to the top of the log window. I have a solution for this issue as a trade-off, we can create a prop named `initialIndexWidth`, if you anticipate your logs will be a very large amount, you can set the `initialIndexWidth` when you render the log viewer so it will give you a wider space for the indices. The only drawback of this method is there will be a little bit more room for the indices when they are small. 
> @rhamilto Please let me know what you think and if you have any other ideas, thanks!

That seems reasonable to me and provides backward compatibility.  It would probably be good to offer guidance on what the value should be based on the number of digits required.

**Comment by mcoker** [comment] 2022-08-31 21:15
> It would probably be good to offer guidance on what the value should be based on the number of digits required.

We could create a `--pf-c-log-viewer__index--chars` var that just takes the number of digits and update the existing index width to account for that. 

Something like this - https://codesandbox.io/s/eloquent-buck-k203gl?file=/index.js

 The component updates we'd make on our side are in style.css, and the `<LogViewer>` component is setting an inline style to specify the number of digits. `initialIndexWidth` could set that.

**Comment by DaoDaoNoCode** [comment] 2022-08-31 22:33
@mcoker That will be good, thanks! Once you updated in core side I will update this prop on React side.

**Closed** 2022-09-21 20:43 UTC
Labels: bug
