### ISSUE TITLE
Prop descriptions are missing from the docs

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#3454] opened 2020-01-06 17:05 UTC
**Describe the issue. What is the expected and unexpected behavior?**
Prop descriptions are missing from the docs

**Comment by ddonahue007** [comment] 2020-01-16 20:25
It appears this could be caused by build infra changes. These descriptions used to be in place. I have attached a screen shot that shows the missing descriptions on the accordion component.

![Screen Shot 2020-01-16 at 3.23.02 PM.png](https://images.zenhubusercontent.com/5dc5dcfe586229000122b6e7/7cf47c9e-b66c-497e-831c-678eff93f416)

**Comment by ddonahue007** [comment] 2020-01-23 16:17
This was fixed by the following PR in the patternfly-org repo
https://github.com/patternfly/patternfly-org/pull/1636

**Comment by ddonahue007** [comment] 2020-01-23 16:44
Need to up the version of the following package to take in the fixes.

packages/patternfly-4/react-docs/package.json
             "gatsby-theme-patternfly-org": "^1.2.9",

**Closed** 2020-01-23 19:04 UTC
Labels: documentation :memo:, infrastructure
