### ISSUE TITLE
Bug - Popper - FindRefWrapper which is inside StrictMode

### ISSUE THREAD

**Issue by Andrei-Stepanov** [patternfly/patternfly-react#7495] opened 2022-06-01 13:24 UTC
**Describe the problem**
Hello, Chrome throws next error to console:

```
react_devtools_backend.js:4026 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of FindRefWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at span
    at FindRefWrapper (http://localhost:3000/static/js/bundle.js:31543:1)
    at Popper (http://localhost:3000/static/js/bundle.js:31595:5)
    at Tooltip (http://localhost:3000/static/js/bundle.js:30741:14)
    at span
    at Label (http://localhost:3000/static/js/bundle.js:23696:5)
    at div
    at dd
    at DescriptionListDescription (http://localhost:3000/static/js/bundle.js:21297:5)
    at div
    at DescriptionListGroup (http://localhost:3000/static/js/bundle.js:21333:5)
    at dl
    at DescriptionList (http://localhost:3000/static/js/bundle.js:21242:5)
    at div
    at FlexItem (http://localhost:3000/static/js/bundle.js:35741:5)
    at div
    at Flex (http://localhost:3000/static/js/bundle.js:35684:5)
    at div
    at Flex (http://localhost:3000/static/js/bundle.js:35684:5)
    at div
    at Flex (http://localhost:3000/static/js/bundle.js:35684:5)
    at StateDetailsEntry (http://localhost:3000/static/js/bundle.js:3253:5)
    at GreenwaveResultInfo (http://localhost:3000/static/js/bundle.js:2009:13)
    at div
    at section
    at DataListContent (http://localhost:3000/static/js/bundle.js:20880:5)
    at li
    at DataListItem (http://localhost:3000/static/js/bundle.js:21000:1)
    at ArtifactState (http://localhost:3000/static/js/bundle.js:3402:5)
    at div
    at ul
    at DataList (http://localhost:3000/static/js/bundle.js:20548:5)
    at ArtifactStatesList (http://localhost:3000/static/js/bundle.js:3625:5)
    at div
    at ExpandableRowContent (http://localhost:3000/static/js/bundle.js:37990:5)
    at td
    at TdBase (http://localhost:3000/static/js/bundle.js:41144:5)
    at Td
    at BodyCell (http://localhost:3000/static/js/bundle.js:37691:19)
    at tr
    at rowWrapper (http://localhost:3000/static/js/bundle.js:5251:109)
    at BodyRow (http://localhost:3000/static/js/bundle.js:38852:1)
    at tbody
    at TbodyBase (http://localhost:3000/static/js/bundle.js:41079:5)
    at Tbody
    at BodyWrapper (http://localhost:3000/static/js/bundle.js:37779:5)
    at BaseBody (http://localhost:3000/static/js/bundle.js:38969:5)
    at Body
    at ContextBody (http://localhost:3000/static/js/bundle.js:37500:5)
    at TableBody (http://localhost:3000/static/js/bundle.js:37633:5)
    at table
    at TableComposableBase (http://localhost:3000/static/js/bundle.js:40982:5)
    at TableComposable
    at Provider (http://localhost:3000/static/js/bundle.js:39448:1)
    at Table (http://localhost:3000/static/js/bundle.js:38478:5)
    at ArtifactsTable (http://localhost:3000/static/js/bundle.js:5043:5)
    at section
    at PageSection (http://localhost:3000/static/js/bundle.js:25752:5)
    at main
    at div
    at Page (http://localhost:3000/static/js/bundle.js:25218:5)
    at div
    at FlexItem (http://localhost:3000/static/js/bundle.js:35741:5)
    at div
    at Flex (http://localhost:3000/static/js/bundle.js:35684:5)
    at PageCommon (http://localhost:3000/static/js/bundle.js:5519:82)
    at PageByMongoField (http://localhost:3000/static/js/bundle.js:5292:84)
    at Route (http://localhost:3000/static/js/bundle.js:130070:29)
    at Content
    at Switch (http://localhost:3000/static/js/bundle.js:130272:29)
    at Router (http://localhost:3000/static/js/bundle.js:129689:30)
    at HashRouter (http://localhost:3000/static/js/bundle.js:129356:35)
    at div
    at ApolloProvider (http://localhost:3000/static/js/bundle.js:169350:19)
    at App
    at Provider (http://localhost:3000/static/js/bundle.js:126556:20)
```

**How do you reproduce the problem?**

```
export const mkLabel = (
    name: string,
    value: string,
    color: LabelProps['color'] = 'orange',
    icon: JSX.Element | null = null,
): JSX.Element => {
    return (
        <DescriptionListGroup key={name}>
            <DescriptionListTerm>{name}</DescriptionListTerm>
            <DescriptionListDescription>
                <Label
                    isCompact
                    color={color}
                    icon={icon}
                    variant="filled"
                    isTruncated
                >
                    {value}
                </Label>
            </DescriptionListDescription>
        </DescriptionListGroup>
    );
};
```

Actual for: 

```
    "@patternfly/react-charts": "^6.67.1",
    "@patternfly/react-core": "^4.214.1",
    "@patternfly/react-icons": "^4.65.1",
    "@patternfly/react-table": "^4.83.1",
```

**Comment by nicolethoen** [comment] 2022-06-07 19:48
Thank you for reporting! 
This is a duplicate of https://github.com/patternfly/patternfly-react/issues/6050
which is already on the road map

**Closed as completed by nicolethoen** 2022-06-07 19:48 UTC
